### ISSUE TITLE
梅林固件安装ssr服务端如何使用路由器本身的ss代理

### ISSUE THREAD

**Issue by liuminglm** [xydche/xydche.github.com#1]
你好，在这篇文章中（xydche.github.io/2017/06/08/梅林固件安装ssr服务端笔记/），我按照你的方法成功安装SSR，可以用，由于我的路由器部署了SS，可以透明代理直接科学上网，但是通过新安装的SSR服务端则只能上国内的，不知道你是否知道怎么可以让SSR服务端使用透明代理，谢谢

**Comment by xydche** [comment]
这个问题我没找到办法，应该做转发可以实现，我也是个菜鸟。我的设备运行ssr服务端不太稳，已经卸了。
